### ISSUE TITLE
[MVP] provide more examples for job trigger

### ISSUE THREAD

**Issue by lulinqing** [RHQE/platform-ci#15]
Currently MVP is using the official build on brew (brew-tag like **RHEL-*-candidate**) by default.
Would any of other triggers people wanna use within MVP?
- [x] scratch builds on brew (including/excluding official builds)
- [x] RTT-accepted stable composes

More?

**Comment by stowellm** [comment]
+1 for RTT-accepted stable composes, since in some cases we may want to run a tier2 suite over these composes anyways

**Comment by petr-muller** [comment]
+1 for scratch builds (as they are very useful for developers to get feedback without the hassle to produce a standard build)

I'd like to remind that the current T2 consensus is that T2 should happen _before_ the actual compose.

**Comment by jcanderle** [comment]
+1 for scratch builds
On Mon, 2016-06-20 at 08:00 -0700, Petr Muller wrote:

> +1 for scratch builds (as they are very useful for developers to get
> feedback without the hassle to produce a standard build)
> I'd like to remind that the current T2 consensus is that T2 should
> happen > before>  the actual compose.
> Thank you for the reminder, please keep that in mind. We should adhere
> to set direction (even your workflows differ or that approach is more
> difficult)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jiří Čanderle
Senior Project Manager
Red Hat ENG QE Platform
PGP (B23F9E2F) fingerprint:
139E 3412 B413 EA65 D0E3  6357 5C9C A19E B23F 9E2F
IRC: jcanderl
T: +420 532 294 545
IP: 8262545
M: +420 775 988 229
