### ISSUE TITLE
PLATFORMCI-1082 - Support use case: Automated build on push

### ISSUE THREAD

**Issue by gsr-shanks** [RHQE/platform-ci#23]
To support Staging Branches pilot, we agreed with Linqing we should deploy BaseOS support of the Automated build on push support

**Comment by gsr-shanks** [comment]
pmuller Petr Muller added a comment - 10/Jun/16 8:08 PM
Reviving this task. The code was migrated to the new repository, PR was issued. After the PR is accepted, I will deploy the jobs to PJM.
https://github.com/RHQE/platform-ci/pull/13

**Comment by petr-muller** [comment]
PR #13 is merged.
